print('=======Desafio 4=======')
n = input('Digite algo: ')
print(type(n))
print('Verdadeiro= True Falso= False')
print('Está em CAPSLOCK: ', n.isupper())
print('Está em caixa baixa: ', n.islower())
print('É um número: ', n.isnumeric())
print('É uma letra ou palavra: ', n.isalpha())
print('É um espaço: ', n.isspace())
print('É um decimal: ', n.isdecimal())
print('É um digito: ', n.isdigit())
